In [3]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [4]:
df=pd.read_excel("ushome.xlsx")
df

area  Bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [5]:
df.Bedrooms.median()

4.0

In [6]:
import math
meadian_bedrooms=math.floor(df.Bedrooms.median())
meadian_bedrooms

4

In [7]:
df.Bedrooms=df.Bedrooms.fillna(meadian_bedrooms)
df

area  Bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [8]:
reg=linear_model.LinearRegression()
reg.fit(df[['area','Bedrooms','age']],df.price)

LinearRegression()

In [9]:
reg.coef_

array([  112.06244194, 23388.88007794, -3231.71790863])

In [10]:
reg.intercept_

221323.00186540384

In [11]:
reg.predict([[3000,4,15]])

C:\Users\HP\anaconda3\Lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([602590.07937407])

In [12]:
112.06244194*3000+23388.88007794*4+-3231.71790863*15+221323.00186540384

602590.0793677138

## Save Model In Pickle

In [13]:
import pickle

In [16]:
with open("model_pickle",'wb')as f:
    pickle.dump(reg,f)


In [19]:
with open("model_pickle",'rb') as f:
    mp=pickle.load(f)

In [22]:
mp.predict([[3000,4,15]])

C:\Users\HP\anaconda3\Lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([602590.07937407])

In [26]:
 from joblib import dump, load

In [7]:
from sklearn.externals import joblib

ImportError: cannot import name 'joblib' from 'sklearn.externals' (C:\Users\HP\anaconda3\Lib\site-packages\sklearn\externals\__init__.py)

In [30]:
pip install joblib


Note: you may need to restart the kernel to use updated packages.Requirement already satisfied: joblib in c:\users\hp\anaconda3\lib\site-packages (1.2.0)



In [11]:
from sklearn.externals import joblib
joblib.dump(clf, 'filename.pkl') 

ImportError: cannot import name 'joblib' from 'sklearn.externals' (C:\Users\HP\anaconda3\Lib\site-packages\sklearn\externals\__init__.py)

In [9]:
pip install --prefix /usr/local joblib

Note: you may need to restart the kernel to use updated packages.


In [10]:
pip install --user joblib

Note: you may need to restart the kernel to use updated packages.
